Meta:
@ReportName Positive
@Dog

Narrative:
In order to test User's_Dogs service
As a tester
I want to make sure all return the code 200 for GET scenarios

Scenario: Positive TC-001: Verify  Get all dogs for a user service using valid data  for New user
Given service method is post
When the service url is: Login_service
And add to the header Content-Type with value application/json
And we set Body with {
    "loginProvider" : "LINK",
    "loginProviderId" : "Auto1@gmail.com",
    "password" : "P@ssw0rd",
    "loginProviderToken" : ""
}
And the service response should be: 200
And Retrieve json path $.access_token response
And service method is get
And the service url changes to: Get_User's_Dogs_service with 191
And add to the header Content-Type with value application/json
And add Session Authorization to Request header
Then the service response should be: 200
And json response should equal:
[
  {
    "id": 74,
    "version": 0,
    "name": "D997",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "",
    "neutered": false,
    "description": "My dog Pucy",
    "age": 4,
    "purebred": true,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "NA",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "0000123",
    "accountId": 191
  },
  {
    "id": 75,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 76,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": true,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 77,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 78,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": true,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 79,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": true,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 80,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": true,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 81,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 82,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId2": 2,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 83,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 84,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 85,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "abc12345",
    "accountId": 191
  },
  {
    "id": 86,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 87,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 50,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 88,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 75,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 89,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 75,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 90,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 1,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 75,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 91,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 50,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 75,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 92,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 25,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 75,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 93,
    "version": 0,
    "name": "D123",
    "photo": "",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 94,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 95,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 96,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 5,
    "purebred": true,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 97,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 5,
    "purebred": false,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 98,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 99,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "q",
    "age": 25,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 5,
    "weightClass": "",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 100,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "q",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 5,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 101,
    "version": 0,
    "name": "22##@*&",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "q",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 5,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 102,
    "version": 0,
    "name": "ID",
    "photo": "",
    "gender": "M",
    "neutered": false,
    "description": "q",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 5,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 103,
    "version": 0,
    "name": "ID",
    "photo": "",
    "gender": "F",
    "neutered": false,
    "description": "#",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 5,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 104,
    "version": 0,
    "name": "ID",
    "photo": "",
    "gender": "F",
    "neutered": false,
    "description": "t",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 3,
    "weightClass": "ee",
    "eyeColor": "*",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 105,
    "version": 0,
    "name": "ID",
    "photo": "",
    "gender": "F",
    "neutered": false,
    "description": "t",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 3,
    "weightClass": "%",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 106,
    "version": 0,
    "name": "ID",
    "photo": "",
    "gender": "F",
    "neutered": false,
    "description": "t",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 3,
    "weightClass": "5",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "#$",
    "accountId": 191
  }
]

Scenario: Positive TC-002: Verify  Get all dogs for a user service using valid data  for old user

Given service method is post
When the service url is: Login_service
And add to the header Content-Type with value application/json
And we set Body with {
    "loginProvider" : "LINK",
    "loginProviderId" : "qa1r@gmail.com",
    "password" : "P@ssw0rd",
    "loginProviderToken" : ""
}
And the service response should be: 200
And Retrieve json path $.access_token response
And service method is get
And the service url changes to: Get_User's_Dogs_service with 168

And add to the header Content-Type with value application/json
And add Session Authorization to Request header
Then the service response should be: 200
And json response should equal:
[
  {
    "id": 71,
    "version": 0,
    "name": "D466",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "",
    "neutered": false,
    "description": "My dog Pucy",
    "age": 4,
    "purebred": true,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "NA",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "0000123",
    "accountId": 168
  }
]

Scenario: Positive TC-004: Verify  Get all dogs for a user service using valid data  for user with multi dogs 

Given service method is post
When the service url is: Login_service
And add to the header Content-Type with value application/json
And we set Body with {
    "loginProvider" : "LINK",
    "loginProviderId" : "Auto1@gmail.com",
    "password" : "P@ssw0rd",
    "loginProviderToken" : ""
}
And the service response should be: 200
And Retrieve json path $.access_token response
And service method is get
And the service url changes to: Get_User's_Dogs_service with 191
And add to the header Content-Type with value application/json
And add Session Authorization to Request header
Then the service response should be: 200
And json response should equal:
[
  {
    "id": 74,
    "version": 0,
    "name": "D997",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "",
    "neutered": false,
    "description": "My dog Pucy",
    "age": 4,
    "purebred": true,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "NA",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "0000123",
    "accountId": 191
  },
  {
    "id": 75,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 76,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": true,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 77,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 78,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": true,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 79,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": true,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 80,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": true,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 81,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 82,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId2": 2,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 83,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 84,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 85,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "abc12345",
    "accountId": 191
  },
  {
    "id": 86,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 87,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 50,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 88,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 75,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 89,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 75,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 90,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 1,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 75,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 91,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 50,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 75,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 92,
    "version": 0,
    "name": "ABC",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 25,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 75,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "12345",
    "accountId": 191
  },
  {
    "id": 93,
    "version": 0,
    "name": "D123",
    "photo": "",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 94,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "",
    "neutered": false,
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 95,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "description": "$",
    "age": 2,
    "purebred": false,
    "breedId1": 1,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 96,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 5,
    "purebred": true,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 97,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 5,
    "purebred": false,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 98,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "$",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 99,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "q",
    "age": 25,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 5,
    "weightClass": "",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 100,
    "version": 0,
    "name": "D123",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "q",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 5,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 101,
    "version": 0,
    "name": "22##@*&",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "M",
    "neutered": false,
    "description": "q",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 5,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 102,
    "version": 0,
    "name": "ID",
    "photo": "",
    "gender": "M",
    "neutered": false,
    "description": "q",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 5,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 103,
    "version": 0,
    "name": "ID",
    "photo": "",
    "gender": "F",
    "neutered": false,
    "description": "#",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 5,
    "weightClass": "ee",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 104,
    "version": 0,
    "name": "ID",
    "photo": "",
    "gender": "F",
    "neutered": false,
    "description": "t",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 3,
    "weightClass": "ee",
    "eyeColor": "*",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 105,
    "version": 0,
    "name": "ID",
    "photo": "",
    "gender": "F",
    "neutered": false,
    "description": "t",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 3,
    "weightClass": "%",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "",
    "accountId": 191
  },
  {
    "id": 106,
    "version": 0,
    "name": "ID",
    "photo": "",
    "gender": "F",
    "neutered": false,
    "description": "t",
    "age": 5,
    "purebred": false,
    "breedId1": 1,
    "breedId2": 2,
    "breed_id1_percentage": 25,
    "dateOfBirth": "03-07-2013",
    "weight": 3,
    "weightClass": "5",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "#$",
    "accountId": 191
  }
]

Scenario:Positive TC-005: Verify  Get all dogs for a user service using valid data  for user with one dog 

Given service method is post
When the service url is: Login_service
And add to the header Content-Type with value application/json
And we set Body with {
    "loginProvider" : "LINK",
    "loginProviderId" : "qa1r@gmail.com",
    "password" : "P@ssw0rd",
    "loginProviderToken" : ""
}
And the service response should be: 200
And Retrieve json path $.access_token response
And service method is get
And the service url changes to: Get_User's_Dogs_service with 168

And add to the header Content-Type with value application/json
And add Session Authorization to Request header
Then the service response should be: 200
And json response should equal:
[
  {
    "id": 71,
    "version": 0,
    "name": "D466",
    "photo": "https://cdn.xyz.com/…..jpg",
    "gender": "",
    "neutered": false,
    "description": "My dog Pucy",
    "age": 4,
    "purebred": true,
    "dateOfBirth": "03-07-2013",
    "weight": 8.9,
    "weightClass": "NA",
    "eyeColor": "BROWN",
    "akcRegistrationNo": "0000123",
    "accountId": 168
  }
]


Scenario: Positive TC-007: Verify  Get all dogs for a user service using valid data  for user without dogs

Given service method is post
When the service url is: Login_service
And add to the header Content-Type with value application/json
And we set Body with {
    "loginProvider" : "LINK",
    "loginProviderId" : "Auto2@gmail.com",
    "password" : "P@ssw0rd",
    "token" : ""
}
And the service response should be: 200
And Retrieve json path $.access_token response
And service method is get
And the service url changes to: Get_User's_Dogs_service with 194
And add to the header Content-Type with value application/json
And add Session Authorization to Request header
Then the service response should be: 200
And json response should equal:
[]